version: '3'
services:
  device-registry:
    image: 'diwise/iot-device-registry:latest'
    build:
      context: ..
      dockerfile: ./deployments/Dockerfile
    restart: always
    depends_on:
      - rabbitmq
      - postgresdb
    environment:
      DIWISE_SQLDB_HOST: 'postgresdb'
      DIWISE_SQLDB_USER: 'testuser'
      DIWISE_SQLDB_NAME: 'devreg'
      DIWISE_SQLDB_PASSWORD: 'testpass'
      DIWISE_SQLDB_SSLMODE: 'disable'
      SERVICE_PORT: '8686'
      RABBITMQ_HOST: 'rabbitmq'
    
    ports:
      - '8686:8686'

  postgresdb:
    image: 'ghcr.io/diwise/test-db-postgresql:prod-824e7cffd65dd3766c88441a48cffd5b2acd55f2'
    restart: always
    environment:
      POSTGRES_DB: 'devreg'
      POSTGRES_USER: 'testuser'
      POSTGRES_PASSWORD: 'testpass'
    ports:
      - '5432'


  rabbitmq:
    image: 'bitnami/rabbitmq:3.8'
    ports:
      - '4369'
      - '5672'
      - '25672'
      - '15672'
    volumes:
      - 'rabbitmq_data:/bitnami'

  grafana:
    image: 'grafana/grafana:8.0.0'
    ports: 
      - '3000:3000'
    depends_on:
      - postgresdb
    volumes: 
      - 'grafana-storage:/var/lib/grafana'
  
volumes:
  rabbitmq_data:
    driver: local
  grafana-storage:
    driver: local
