// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package database

import (
	"github.com/diwise/iot-device-registry/internal/pkg/infrastructure/repositories/models"
	"github.com/diwise/ngsi-ld-golang/pkg/datamodels/fiware"
	"sync"
)

// Ensure, that DatastoreMock does implement Datastore.
// If this is not the case, regenerate this file with moq.
var _ Datastore = &DatastoreMock{}

// DatastoreMock is a mock implementation of Datastore.
//
// 	func TestSomethingThatUsesDatastore(t *testing.T) {
//
// 		// make and configure a mocked Datastore
// 		mockedDatastore := &DatastoreMock{
// 			CreateDeviceFunc: func(device *fiware.Device) (*models.Device, error) {
// 				panic("mock out the CreateDevice method")
// 			},
// 			CreateDeviceModelFunc: func(deviceModel *fiware.DeviceModel) (*models.DeviceModel, error) {
// 				panic("mock out the CreateDeviceModel method")
// 			},
// 			GetDeviceFromIDFunc: func(id string) (*models.Device, error) {
// 				panic("mock out the GetDeviceFromID method")
// 			},
// 			GetDeviceModelFromIDFunc: func(id string) (*models.DeviceModel, error) {
// 				panic("mock out the GetDeviceModelFromID method")
// 			},
// 			GetDeviceModelFromPrimaryKeyFunc: func(id uint) (*models.DeviceModel, error) {
// 				panic("mock out the GetDeviceModelFromPrimaryKey method")
// 			},
// 			GetDeviceModelsFunc: func() ([]models.DeviceModel, error) {
// 				panic("mock out the GetDeviceModels method")
// 			},
// 			GetDevicesFunc: func() ([]models.Device, error) {
// 				panic("mock out the GetDevices method")
// 			},
// 			UpdateDeviceLocationFunc: func(deviceID string, lat float64, lon float64) error {
// 				panic("mock out the UpdateDeviceLocation method")
// 			},
// 			UpdateDeviceValueFunc: func(deviceID string, value string) error {
// 				panic("mock out the UpdateDeviceValue method")
// 			},
// 		}
//
// 		// use mockedDatastore in code that requires Datastore
// 		// and then make assertions.
//
// 	}
type DatastoreMock struct {
	// CreateDeviceFunc mocks the CreateDevice method.
	CreateDeviceFunc func(device *fiware.Device) (*models.Device, error)

	// CreateDeviceModelFunc mocks the CreateDeviceModel method.
	CreateDeviceModelFunc func(deviceModel *fiware.DeviceModel) (*models.DeviceModel, error)

	// GetDeviceFromIDFunc mocks the GetDeviceFromID method.
	GetDeviceFromIDFunc func(id string) (*models.Device, error)

	// GetDeviceModelFromIDFunc mocks the GetDeviceModelFromID method.
	GetDeviceModelFromIDFunc func(id string) (*models.DeviceModel, error)

	// GetDeviceModelFromPrimaryKeyFunc mocks the GetDeviceModelFromPrimaryKey method.
	GetDeviceModelFromPrimaryKeyFunc func(id uint) (*models.DeviceModel, error)

	// GetDeviceModelsFunc mocks the GetDeviceModels method.
	GetDeviceModelsFunc func() ([]models.DeviceModel, error)

	// GetDevicesFunc mocks the GetDevices method.
	GetDevicesFunc func() ([]models.Device, error)

	// UpdateDeviceLocationFunc mocks the UpdateDeviceLocation method.
	UpdateDeviceLocationFunc func(deviceID string, lat float64, lon float64) error

	// UpdateDeviceValueFunc mocks the UpdateDeviceValue method.
	UpdateDeviceValueFunc func(deviceID string, value string) error

	// calls tracks calls to the methods.
	calls struct {
		// CreateDevice holds details about calls to the CreateDevice method.
		CreateDevice []struct {
			// Device is the device argument value.
			Device *fiware.Device
		}
		// CreateDeviceModel holds details about calls to the CreateDeviceModel method.
		CreateDeviceModel []struct {
			// DeviceModel is the deviceModel argument value.
			DeviceModel *fiware.DeviceModel
		}
		// GetDeviceFromID holds details about calls to the GetDeviceFromID method.
		GetDeviceFromID []struct {
			// ID is the id argument value.
			ID string
		}
		// GetDeviceModelFromID holds details about calls to the GetDeviceModelFromID method.
		GetDeviceModelFromID []struct {
			// ID is the id argument value.
			ID string
		}
		// GetDeviceModelFromPrimaryKey holds details about calls to the GetDeviceModelFromPrimaryKey method.
		GetDeviceModelFromPrimaryKey []struct {
			// ID is the id argument value.
			ID uint
		}
		// GetDeviceModels holds details about calls to the GetDeviceModels method.
		GetDeviceModels []struct {
		}
		// GetDevices holds details about calls to the GetDevices method.
		GetDevices []struct {
		}
		// UpdateDeviceLocation holds details about calls to the UpdateDeviceLocation method.
		UpdateDeviceLocation []struct {
			// DeviceID is the deviceID argument value.
			DeviceID string
			// Lat is the lat argument value.
			Lat float64
			// Lon is the lon argument value.
			Lon float64
		}
		// UpdateDeviceValue holds details about calls to the UpdateDeviceValue method.
		UpdateDeviceValue []struct {
			// DeviceID is the deviceID argument value.
			DeviceID string
			// Value is the value argument value.
			Value string
		}
	}
	lockCreateDevice                 sync.RWMutex
	lockCreateDeviceModel            sync.RWMutex
	lockGetDeviceFromID              sync.RWMutex
	lockGetDeviceModelFromID         sync.RWMutex
	lockGetDeviceModelFromPrimaryKey sync.RWMutex
	lockGetDeviceModels              sync.RWMutex
	lockGetDevices                   sync.RWMutex
	lockUpdateDeviceLocation         sync.RWMutex
	lockUpdateDeviceValue            sync.RWMutex
}

// CreateDevice calls CreateDeviceFunc.
func (mock *DatastoreMock) CreateDevice(device *fiware.Device) (*models.Device, error) {
	callInfo := struct {
		Device *fiware.Device
	}{
		Device: device,
	}
	mock.lockCreateDevice.Lock()
	mock.calls.CreateDevice = append(mock.calls.CreateDevice, callInfo)
	mock.lockCreateDevice.Unlock()
	if mock.CreateDeviceFunc == nil {
		var (
			deviceOut *models.Device
			errOut    error
		)
		return deviceOut, errOut
	}
	return mock.CreateDeviceFunc(device)
}

// CreateDeviceCalls gets all the calls that were made to CreateDevice.
// Check the length with:
//     len(mockedDatastore.CreateDeviceCalls())
func (mock *DatastoreMock) CreateDeviceCalls() []struct {
	Device *fiware.Device
} {
	var calls []struct {
		Device *fiware.Device
	}
	mock.lockCreateDevice.RLock()
	calls = mock.calls.CreateDevice
	mock.lockCreateDevice.RUnlock()
	return calls
}

// CreateDeviceModel calls CreateDeviceModelFunc.
func (mock *DatastoreMock) CreateDeviceModel(deviceModel *fiware.DeviceModel) (*models.DeviceModel, error) {
	callInfo := struct {
		DeviceModel *fiware.DeviceModel
	}{
		DeviceModel: deviceModel,
	}
	mock.lockCreateDeviceModel.Lock()
	mock.calls.CreateDeviceModel = append(mock.calls.CreateDeviceModel, callInfo)
	mock.lockCreateDeviceModel.Unlock()
	if mock.CreateDeviceModelFunc == nil {
		var (
			deviceModelOut *models.DeviceModel
			errOut         error
		)
		return deviceModelOut, errOut
	}
	return mock.CreateDeviceModelFunc(deviceModel)
}

// CreateDeviceModelCalls gets all the calls that were made to CreateDeviceModel.
// Check the length with:
//     len(mockedDatastore.CreateDeviceModelCalls())
func (mock *DatastoreMock) CreateDeviceModelCalls() []struct {
	DeviceModel *fiware.DeviceModel
} {
	var calls []struct {
		DeviceModel *fiware.DeviceModel
	}
	mock.lockCreateDeviceModel.RLock()
	calls = mock.calls.CreateDeviceModel
	mock.lockCreateDeviceModel.RUnlock()
	return calls
}

// GetDeviceFromID calls GetDeviceFromIDFunc.
func (mock *DatastoreMock) GetDeviceFromID(id string) (*models.Device, error) {
	callInfo := struct {
		ID string
	}{
		ID: id,
	}
	mock.lockGetDeviceFromID.Lock()
	mock.calls.GetDeviceFromID = append(mock.calls.GetDeviceFromID, callInfo)
	mock.lockGetDeviceFromID.Unlock()
	if mock.GetDeviceFromIDFunc == nil {
		var (
			deviceOut *models.Device
			errOut    error
		)
		return deviceOut, errOut
	}
	return mock.GetDeviceFromIDFunc(id)
}

// GetDeviceFromIDCalls gets all the calls that were made to GetDeviceFromID.
// Check the length with:
//     len(mockedDatastore.GetDeviceFromIDCalls())
func (mock *DatastoreMock) GetDeviceFromIDCalls() []struct {
	ID string
} {
	var calls []struct {
		ID string
	}
	mock.lockGetDeviceFromID.RLock()
	calls = mock.calls.GetDeviceFromID
	mock.lockGetDeviceFromID.RUnlock()
	return calls
}

// GetDeviceModelFromID calls GetDeviceModelFromIDFunc.
func (mock *DatastoreMock) GetDeviceModelFromID(id string) (*models.DeviceModel, error) {
	callInfo := struct {
		ID string
	}{
		ID: id,
	}
	mock.lockGetDeviceModelFromID.Lock()
	mock.calls.GetDeviceModelFromID = append(mock.calls.GetDeviceModelFromID, callInfo)
	mock.lockGetDeviceModelFromID.Unlock()
	if mock.GetDeviceModelFromIDFunc == nil {
		var (
			deviceModelOut *models.DeviceModel
			errOut         error
		)
		return deviceModelOut, errOut
	}
	return mock.GetDeviceModelFromIDFunc(id)
}

// GetDeviceModelFromIDCalls gets all the calls that were made to GetDeviceModelFromID.
// Check the length with:
//     len(mockedDatastore.GetDeviceModelFromIDCalls())
func (mock *DatastoreMock) GetDeviceModelFromIDCalls() []struct {
	ID string
} {
	var calls []struct {
		ID string
	}
	mock.lockGetDeviceModelFromID.RLock()
	calls = mock.calls.GetDeviceModelFromID
	mock.lockGetDeviceModelFromID.RUnlock()
	return calls
}

// GetDeviceModelFromPrimaryKey calls GetDeviceModelFromPrimaryKeyFunc.
func (mock *DatastoreMock) GetDeviceModelFromPrimaryKey(id uint) (*models.DeviceModel, error) {
	callInfo := struct {
		ID uint
	}{
		ID: id,
	}
	mock.lockGetDeviceModelFromPrimaryKey.Lock()
	mock.calls.GetDeviceModelFromPrimaryKey = append(mock.calls.GetDeviceModelFromPrimaryKey, callInfo)
	mock.lockGetDeviceModelFromPrimaryKey.Unlock()
	if mock.GetDeviceModelFromPrimaryKeyFunc == nil {
		var (
			deviceModelOut *models.DeviceModel
			errOut         error
		)
		return deviceModelOut, errOut
	}
	return mock.GetDeviceModelFromPrimaryKeyFunc(id)
}

// GetDeviceModelFromPrimaryKeyCalls gets all the calls that were made to GetDeviceModelFromPrimaryKey.
// Check the length with:
//     len(mockedDatastore.GetDeviceModelFromPrimaryKeyCalls())
func (mock *DatastoreMock) GetDeviceModelFromPrimaryKeyCalls() []struct {
	ID uint
} {
	var calls []struct {
		ID uint
	}
	mock.lockGetDeviceModelFromPrimaryKey.RLock()
	calls = mock.calls.GetDeviceModelFromPrimaryKey
	mock.lockGetDeviceModelFromPrimaryKey.RUnlock()
	return calls
}

// GetDeviceModels calls GetDeviceModelsFunc.
func (mock *DatastoreMock) GetDeviceModels() ([]models.DeviceModel, error) {
	callInfo := struct {
	}{}
	mock.lockGetDeviceModels.Lock()
	mock.calls.GetDeviceModels = append(mock.calls.GetDeviceModels, callInfo)
	mock.lockGetDeviceModels.Unlock()
	if mock.GetDeviceModelsFunc == nil {
		var (
			deviceModelsOut []models.DeviceModel
			errOut          error
		)
		return deviceModelsOut, errOut
	}
	return mock.GetDeviceModelsFunc()
}

// GetDeviceModelsCalls gets all the calls that were made to GetDeviceModels.
// Check the length with:
//     len(mockedDatastore.GetDeviceModelsCalls())
func (mock *DatastoreMock) GetDeviceModelsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetDeviceModels.RLock()
	calls = mock.calls.GetDeviceModels
	mock.lockGetDeviceModels.RUnlock()
	return calls
}

// GetDevices calls GetDevicesFunc.
func (mock *DatastoreMock) GetDevices() ([]models.Device, error) {
	callInfo := struct {
	}{}
	mock.lockGetDevices.Lock()
	mock.calls.GetDevices = append(mock.calls.GetDevices, callInfo)
	mock.lockGetDevices.Unlock()
	if mock.GetDevicesFunc == nil {
		var (
			devicesOut []models.Device
			errOut     error
		)
		return devicesOut, errOut
	}
	return mock.GetDevicesFunc()
}

// GetDevicesCalls gets all the calls that were made to GetDevices.
// Check the length with:
//     len(mockedDatastore.GetDevicesCalls())
func (mock *DatastoreMock) GetDevicesCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetDevices.RLock()
	calls = mock.calls.GetDevices
	mock.lockGetDevices.RUnlock()
	return calls
}

// UpdateDeviceLocation calls UpdateDeviceLocationFunc.
func (mock *DatastoreMock) UpdateDeviceLocation(deviceID string, lat float64, lon float64) error {
	callInfo := struct {
		DeviceID string
		Lat      float64
		Lon      float64
	}{
		DeviceID: deviceID,
		Lat:      lat,
		Lon:      lon,
	}
	mock.lockUpdateDeviceLocation.Lock()
	mock.calls.UpdateDeviceLocation = append(mock.calls.UpdateDeviceLocation, callInfo)
	mock.lockUpdateDeviceLocation.Unlock()
	if mock.UpdateDeviceLocationFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.UpdateDeviceLocationFunc(deviceID, lat, lon)
}

// UpdateDeviceLocationCalls gets all the calls that were made to UpdateDeviceLocation.
// Check the length with:
//     len(mockedDatastore.UpdateDeviceLocationCalls())
func (mock *DatastoreMock) UpdateDeviceLocationCalls() []struct {
	DeviceID string
	Lat      float64
	Lon      float64
} {
	var calls []struct {
		DeviceID string
		Lat      float64
		Lon      float64
	}
	mock.lockUpdateDeviceLocation.RLock()
	calls = mock.calls.UpdateDeviceLocation
	mock.lockUpdateDeviceLocation.RUnlock()
	return calls
}

// UpdateDeviceValue calls UpdateDeviceValueFunc.
func (mock *DatastoreMock) UpdateDeviceValue(deviceID string, value string) error {
	callInfo := struct {
		DeviceID string
		Value    string
	}{
		DeviceID: deviceID,
		Value:    value,
	}
	mock.lockUpdateDeviceValue.Lock()
	mock.calls.UpdateDeviceValue = append(mock.calls.UpdateDeviceValue, callInfo)
	mock.lockUpdateDeviceValue.Unlock()
	if mock.UpdateDeviceValueFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.UpdateDeviceValueFunc(deviceID, value)
}

// UpdateDeviceValueCalls gets all the calls that were made to UpdateDeviceValue.
// Check the length with:
//     len(mockedDatastore.UpdateDeviceValueCalls())
func (mock *DatastoreMock) UpdateDeviceValueCalls() []struct {
	DeviceID string
	Value    string
} {
	var calls []struct {
		DeviceID string
		Value    string
	}
	mock.lockUpdateDeviceValue.RLock()
	calls = mock.calls.UpdateDeviceValue
	mock.lockUpdateDeviceValue.RUnlock()
	return calls
}
